import type { McpToolDefinition } from '../types.js';

export const sdkInsightsTools: [string, McpToolDefinition][] = [
  ["getSDKAnalysis", {
    name: "getSDKAnalysis",
    description: `Get timeseries metrics for SDKs.

## Usage
- **Required**:
  - \`breakdown\`
  - \`date_granularity\`
  - \`start_date\`
  - \`end_date\`
  - \`sdk_ids\`
  - \`os\`
- **Exactly one \`metric\`**
- **Optional filters**:
  - \`unified_categories\`
  - \`regions\`

## Breakdowns

Comma-separated list of breakdowns.

### Supported combinations:

- \`sdk_id\` - Table-like breakdown by SDK
- \`date, sdk_id\` - Timeseries data by SDK

## Granularity
- \`date_granularity\`: How data is aggregated (day/week/month/quarter)

## Metrics
- \`sdk_apps_detected\` - The number of apps with the SDK installed over this period.
- \`sdk_installs\` - Number of apps that installed the SDK over this period.
- \`sdk_uninstalls\` - Number of apps that uninstalled the SDK over this period.
- \`sdk_apps_detected_share\` - The share of all apps with the SDK installed today.
- \`est_sdk_downloads\` - App downloads with the SDK installed over this period.
- \`est_sdk_downloads_share\` - The share of all app downloads with the SDK installed over this period.

## Notes

**Important:** This API might get updated in the future (next 6 months after release, see <a href="/api/docs/changelog">API Changelog</a>) as we continue to expand its functionality and support more metrics.
We recommend integrating with caution and monitoring release notes for upcoming changes.
`,
    inputSchema: {"type":"object","properties":{"metric":{"type":"string","enum":["sdk_apps_detected","sdk_apps_detected_share","sdk_installs","sdk_uninstalls","est_sdk_downloads","est_sdk_downloads_share"],"description":"The metric to retrieve data for"},"breakdown":{"type":"string","enum":["sdk_id","date, sdk_id"],"description":"How to break down the data (comma-separated for breakdown by multiple fields, e.g. `sdk_id`)"},"date_granularity":{"type":"string","enum":["day","week","month","quarter"],"description":"Date granularity for the data."},"start_date":{"type":"string","format":"date","description":"Start date for the data range. `YYYY-MM-DD` format"},"end_date":{"type":"string","format":"date","description":"End date for the data range. `YYYY-MM-DD` format"},"regions":{"type":"array","items":{"type":"string"},"description":"Array of region codes to filter by (comma-separated), <a target='_blank' href='/api/docs/static/country_ids.json'>Region Codes</a>"},"sdk_ids":{"type":"array","items":{"type":"number","format":"Int64"},"minItems":1,"description":"Array of SDK IDs to filter by (comma-separated integers)."},"unified_categories":{"type":"array","items":{"type":"string"},"minItems":1,"description":"Array of category IDs to filter apps by (comma-separated strings), use iOS categories from\n              <a target='_blank' href='/api/docs/static/category_ids.json'>Category IDs</a>."},"os":{"type":"string","enum":["unified","ios","android"],"description":"The platform to filter by."}},"required":["metric","breakdown","date_granularity","start_date","end_date","sdk_ids","os"]},
    method: "get",
    pathTemplate: "/v1/facets/metrics",
    executionParameters: [{"name":"metric","in":"query"},{"name":"breakdown","in":"query"},{"name":"date_granularity","in":"query"},{"name":"start_date","in":"query"},{"name":"end_date","in":"query"},{"name":"regions","in":"query"},{"name":"sdk_ids","in":"query"},{"name":"unified_categories","in":"query"},{"name":"os","in":"query"}],
    requestBodyContentType: undefined,
    securityRequirements: [{"auth_token":[]}]
  }],
  ["getSDKOverviewApps", {
    name: "getSDKOverviewApps",
    description: `Get apps having a particular SDK installed or uninstalled.

## Usage
- **Required**:
  - \`bundle\`
  - \`breakdown\`
  - \`sdk_id\`
- **Optional filters**:
  - \`sdk_install_status\`
  - \`limit\`
  - \`offset\`
  - \`order_by\`

## Breakdowns

Comma-separated list of breakdowns.

### Supported combinations:

- \`unified_app_id\` - Breakdown by unified app ID.
- \`unified_app_id, app_id\` - Breakdown by unified app ID and app ID.

## SDK Overview App Data Bundle - included metrics
- \`est_sdk_downloads_last_30_days_ww\` - Downloads with the SDK installed in the last 30 days.
- \`est_sdk_revenue_last_30_days_ww\` - Revenue generated by the app with the SDK installed in the last 30 days.
- \`est_sdk_dau_last_30_days_ww\` - Average DAU (daily active users) for the app with the SDK installed in the last 30 days.
- \`sdk_days_installed\` - Days installed.
- \`sdk_install_date\` - Date installed.
- \`sdk_uninstall_date\` - Date uninstalled.

## Notes

**Important:** This API might get updated in the future (next 6 months after release, see <a href="/api/docs/changelog">API Changelog</a>) as we continue to expand its functionality and support more metrics.
We recommend integrating with caution and monitoring release notes for upcoming changes.
`,
    inputSchema: {"type":"object","properties":{"bundle":{"type":"string","enum":["sdk_overview_app_data"],"description":"The bundle to retrieve data for"},"breakdown":{"type":"string","enum":["unified_app_id","unified_app_id, app_id"],"description":"How to break down the data (comma-separated for breakdown by multiple fields, e.g. `unified_app_id`)"},"sdk_id":{"type":"number","format":"Int64","description":"SDK ID to filter by (integer)."},"sdk_install_status":{"type":"string","enum":["installed","uninstalled"],"description":"Filter by apps which have the SDK installed/uninstalled."},"limit":{"type":"number","format":"Int64","description":"Limit of number of apps to return (max 200)."},"offset":{"type":"number","format":"Int64","description":"Offset."},"order_by":{"type":"array","items":{"type":"string"},"description":"Array of metrics and direction to order by (`metric:direction`)."}},"required":["bundle","breakdown","sdk_id"]},
    method: "get",
    pathTemplate: "/v1/facets/metrics",
    executionParameters: [{"name":"bundle","in":"query"},{"name":"breakdown","in":"query"},{"name":"sdk_id","in":"query"},{"name":"sdk_install_status","in":"query"},{"name":"limit","in":"query"},{"name":"offset","in":"query"},{"name":"order_by","in":"query"}],
    requestBodyContentType: undefined,
    securityRequirements: [{"auth_token":[]}]
  }],
  ["sdk_overview", {
    name: "sdk_overview",
    description: `<p>Get metadata and main performance metrics for SDKs.</p>
<p>Limit: <code>100</code> sdk_ids per call</p>

List of SDK Types in data can be found in
(<a target='_blank' href='/api/docs/static/sdk_type_ids.json'>SDK Type IDs</a>)
List of Category IDs in data can be found in
(<a target='_blank' href='/api/docs/static/category_ids.json'>Category Ids</a>)
`,
    inputSchema: {"type":"object","properties":{"sdk_ids":{"type":"array","items":{"type":"number","format":"int64"},"minItems":1,"description":"SDK IDs of SDKs (limited to 100)"}},"required":["sdk_ids"]},
    method: "get",
    pathTemplate: "/v1/sdk/summary_metrics",
    executionParameters: [{"name":"sdk_ids","in":"query"}],
    requestBodyContentType: undefined,
    securityRequirements: [{"auth_token":[]}]
  }],
];
